framework:
    cache:
        app: cache.adapter.filesystem
        pools:
            noncePool:
                adapters:
                    - cache.adapter.apcu
            sessionPool:
                adapters:
                    - cache.adapter.apcu
            requestPool:
                adapters:
                    - cache.adapter.apcu
            persistSessionPool:
                adapters:
                    - cache.adapter.filesystem
            persistRequestPool:
                adapters:
                    - cache.adapter.filesystem

        # Unique name of your app: used to compute
        # stable namespaces for cache keys.
        prefix_seed: digitaladapt/preauth

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads
        # as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
