services:
  preauth:
    env_file:
      # TODO rename ".env.example" to just ".env"
      # edit USER_ID and GROUP_ID if needed
      # set PREAUTH_KEY and PREAUTH_TOKEN after initial start to persist those settings
      - .env
    expose:
      - 9000
    image: digitaladapt/preauth
    init: true
    restart: unless-stopped
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - preauth-sessions:/tmp/sessions

volumes:
  preauth-sessions:

